# Generated by Django 2.1.4 on 2018-12-05 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cup',
            name='barcode',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
