# Generated by Django 2.1.4 on 2018-12-05 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0002_cup_barcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cup',
            name='barcode',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
